bin/msmtpq - fix connect test
import from msmtp d8bd77cde5f38a2c3cc8748d8ee2443f8ff39240

diff --git a/bin/msmtpq b/bin/msmtpq
--- a/bin/msmtpq
+++ b/bin/msmtpq
@@ -41,7 +41,7 @@
 ##                       if =s will use bash sockets to test for a connection
 ##   EMAIL_QUEUE_QUIET   if set will cause suppression of messages and 'chatter'
 
-EMAIL_CONN_TEST=nm-p
+EMAIL_CONN_TEST=  # see default above / in connect_test() function
 
 ## two essential patches by Philipp Hartwig
 ## 19 Oct 2011 & 27 Oct 2011
@@ -174,10 +174,12 @@ lock_queue() {        # <-- '-u' to remove lockfile
 ## test whether system is connected
 ## returns t/f (0/1)
 connect_test() {
-  local EMAIL_CONN_TEST="${1:-EMAIL_CONN_TEST}"
   if [ -z "$EMAIL_CONN_TEST" ] || \
      [ "$EMAIL_CONN_TEST" = 'nm-p' ] ; then                    # use NetworkManager (nm-online) test plus ping fallback (default)
-    connect_test nm || connect_test p || return 1
+    which nm-online >/dev/null 2>&1 || \
+      log "msmtpq : can't find nm-online executable "     # if not found - complain
+    'nm-online' -xq || ping -qnc1 -w4 debian.org >/dev/null 2>&1 || return 1
+
   elif [ -z "$EMAIL_CONN_TEST" ] || \
      [ "$EMAIL_CONN_TEST" = 'nm' ] ; then                      # use NetworkManager (nm-online) test
     # must, of course, have nm-online installed
